### ISSUE TITLE
Update functions to accept both time and duration values

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#1107]
Flux will soon allow time and duration values to be interchangeable in certain cases. The following functions need to be updated to accept both time and duration values:

- [x] date.second (influxdata/flux#2910)
- [x] date.minute (influxdata/flux#2911)
- [x] date.hour (influxdata/flux#2912)
- [x] date.weekDay (influxdata/flux#2913)
- [x] date.monthDay (influxdata/flux#2914)
- [x] date.yearDay (influxdata/flux#2915)
- [x] date.month (influxdata/flux#2916)
- [x] date.year (influxdata/flux#2917)
- [x] date.quarter (influxdata/flux#2918)
- [x] date.millisecond (influxdata/flux#2919)
- [x] date.microsecond (influxdata/flux#2920)
- [x] date.nanosecond (influxdata/flux#2921)
- [x] date.truncate (influxdata/flux#2922)

**Comment by sanderson** [comment]
Closed via #1140
