### ISSUE TITLE
OSS 2.0.2

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#1830]
- [x] Nora: Add 2.0.2 release notes from [changelog](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md) 
- [x] Cross-check release announcement to ensure highlights in release notes and announcement align
- [x] Update versions

**Update docs for the following issues as applicable:**
- [ ] Will: [Improvements to influxd upgrade command](https://github.com/influxdata/influxdb/issues/19985)

- [x] Nora: [Add dbrp management to the CLI #19950](https://github.com/influxdata/influxdb/issues/19950)

- [x] NORA: Description of OSS behavior for V1 /write endpoint is out-of-date https://github.com/influxdata/docs-v2/issues/1831

- [x] Scott: Improvements to `influxd upgrade` command 
https://github.com/influxdata/influxdb/issues/20030

- [x] Incorrect input validation in `influxd upgrade`
https://github.com/influxdata/influxdb/issues/20038

- [x] feat: [Port Pipeline test framework and comprehensive InfluxQL tests](https://github.com/influxdata/influxdb/pull/20004)

- [x] https://github.com/influxdata/influxdb/pull/19878

- [x] Will: https://github.com/influxdata/influxdb/pull/20036 (warn user during upgrade if auth was not enabled for 1.x)

- [x] Scott: provide an option to dump continuous queries during upgrade https://github.com/influxdata/influxdb/pull/20039 
- [ ] Will: include info about what happens if HTTP auth is disabled. https://github.com/influxdata/influxdb/pull/20039 

- [x] Kelly: fix: Don't include duplicates for SHOW DATABASES https://github.com/influxdata/influxdb/pull/20017 (verified this is release notes only)

- [ ] Will: influxd CLI reference docs are missing info on `upgrade` subcommands https://github.com/influxdata/docs-v2/issues/1813

- [x] Scott: influxd CLI reference docs show unavailable subcommands https://github.com/influxdata/docs-v2/issues/1812
