### ISSUE TITLE
(Epic) API compatibility improvements

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2206]
This issue is in response to https://github.com/influxdata/docs-v2/issues/2100, which see.

-  [x] Finish Grafana authorization docs (https://github.com/influxdata/docs-v2/issues/2165).
- [x] Create a task-based "Manually upgrade from 1.x to 2.0" document under "Upgrade InfluxDB". Must include 1) creating DBRP mappings and 2) creating token authorizations (see also https://github.com/influxdata/docs-v2/issues/2165). (Work ongoing in https://github.com/influxdata/docs-v2/pull/2264.)
- [x] Create an issue in the influxdb repo to update swagger for AuthPassV1 parameter description.
- [x] Update the InfluxDB 1.x compatibility API doc to reflect basic auth for tokens and v1 password.
- [x] On the "Upgrade from InfluxDB 1.x to InfluxDB 2.0" doc, add a link to the new "Manually upgrade from 1.x to 2.0" doc with context on when they'd want to use this new procedure (or not) + clarify that V1 users/credentials must use the V1 API. (Update: now included in #2264.)
- [ ] Cloud:
    - [ ] "Upgrade from 1.x to Cloud"
    - ~[ ] "Using 1.x clients with Cloud"~
    - [x] "Remove cli v1 auth page from cloud docs" https://github.com/influxdata/docs-v2/issues/2208

**Comment by timhallinflux** [comment]
There is no v1 Auth capability in Cloud.  That is only available on OSS.  
This means that this section should not appear in our Cloud reference: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/v1/auth/

**Comment by timhallinflux** [comment]
This also means that folks who wish to continue to use their v1 tools/dashboards with Cloud --- like Chronograf, Grafana, and Kapacitor -- MUST change their auth schemes to use token-based auth.

For OSS, there are 2 options --
1) use the v1 Auth (automatically created for NON-ADMIN users or manually create v1 Auth username/passwords). Keep in mind that there are two reasons folks will need to create v1 Auth setups post-upgrade --- 
    a) they didn't read the upgrade doc and don't understand what happened to their admin users or 
    b) they didn't read the upgrade doc and didn't have auth enabled and now need to create username/password combo to make this work

2) switch to token-based auth as in the Cloud scenario

**Comment by timhallinflux** [comment]
see also ->  https://github.com/influxdata/EAR/issues/2056

**Comment by russorat** [comment]
connect https://github.com/influxdata/docs-v2/issues/2208

**Comment by sanderson** [comment]
Closing this issue for now. The only remaining items are covered in #2332.
