### ISSUE TITLE
Enterprise 1.9.3 release notes

### ISSUE THREAD

**Issue by pierwill** [influxdata/docs-v2#2824]
- https://github.com/influxdata/plutonium/blob/master/CHANGELOG.md
- https://github.com/influxdata/influxdb/blob/master-1.x/CHANGELOG.md

## TODOs

- [ ] Link to Flux 1.20.1 release notes.
- [x] Link to password hashing configuration doc.
- [x] Add release date

**Comment by pierwill** [comment]
## TODOs

- [ ] Link to Flux 1.20.1 release notes.
- [ ] Link to password hashing configuration doc.
