### ISSUE TITLE
InfluxDB OSS 2.2 checklist

### ISSUE THREAD

**Issue by kelseiv** [influxdata/docs-v2#3752]
- [x] [base branch](https://github.com/influxdata/docs-v2/pull/3744)
- [x] [api updates](https://github.com/influxdata/docs-v2/pull/3744/commits/df4e835063b8d730e790a2fe9415732fd82c99c4)
- [x] [release notes](https://github.com/influxdata/docs-v2/pull/3745)
- [x] [Document influx remote and influx replication](https://github.com/influxdata/docs-v2/pull/3469) 
- [x] [Document new InfluxDB OSS --harding-enabled feature](https://github.com/influxdata/docs-v2/issues/3866)
- [ ] [Refer to DB release notes in CLI 2.3 release notes](https://github.com/influxdata/docs-v2/issues/3937)

**Comment by jdstrand** [comment]
@kelseiv - should https://github.com/influxdata/docs-v2/pull/3898 (Add security section to influxdb/v2.2/reference/release-notes/influxdb.md) be added to this list?

Also, note that `--hardening-enabled` was committed to oss-2.2-base in https://github.com/influxdata/docs-v2/pull/3873

**Comment by samhld** [comment]
@kelseiv I believe 2.2 is done from the software side. Anything else to close here?
