### ISSUE TITLE
Enterprise 1.9.7 release checklist

### ISSUE THREAD

**Issue by samhld** [influxdata/docs-v2#3927]
- [x] Release notes
- [x] influxd-ctl add-data
- [x] [Glossary](https://github.com/influxdata/docs-v2/issues/3925) 
- [x] [Cluster features](https://github.com/influxdata/docs-v2/issues/3926)
