### ISSUE TITLE
Update CLI commands from 'find' to 'list'

### ISSUE THREAD

**Issue by sanderson** [influxdata/docs-v2#753]
All the `influx` CLI's `find` subcommands have been updated to `list` and now how `ls` and `find` as aliases.

PR: https://github.com/influxdata/influxdb/pull/16805

### CLI docs
- [x] /v2.0/reference/cli/influx/auth/
- [x] /v2.0/reference/cli/influx/auth/find/
- [x] /v2.0/reference/cli/influx/bucket/
- [x] /v2.0/reference/cli/influx/bucket/find/
- [x] /v2.0/reference/cli/influx/org/
- [x] /v2.0/reference/cli/influx/org/find/
- [x] /v2.0/reference/cli/influx/secret/
- [x] /v2.0/reference/cli/influx/secret/find/
- [x] /v2.0/reference/cli/influx/task/
- [x] /v2.0/reference/cli/influx/task/find/
- [x] /v2.0/reference/cli/influx/task/log/
- [x] /v2.0/reference/cli/influx/task/log/find/
- [x] /v2.0/reference/cli/influx/task/run/
- [x] /v2.0/reference/cli/influx/task/run/find/
- [x] /v2.0/reference/cli/influx/user/
- [x] /v2.0/reference/cli/influx/user/find/

### Task docs
- [x] /v2.0/process-data/manage-tasks/run-task/
- [x] /v2.0/process-data/manage-tasks/task-run-history/
- [x] /v2.0/process-data/manage-tasks/view-tasks/

### Org docs
- [x] /v2.0/organizations/view-orgs/

### Bucket docs
- [x] /v2.0/organizations/buckets/view-buckets/

### Member docs
- [x] /v2.0/organizations/members/add-member/

### User docs
- [x] /v2.0/users/view-users/

### Secrets docs
- [x] /v2.0/security/secrets/manage-secrets/view/

### Token docs
- [x] /v2.0/security/tokens/view-tokens/
